//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v8.18.5
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace PassleSync.Core.Models.Content.Umbraco
{
	/// <summary>Passle Post</summary>
	[PublishedModel("passlePost")]
	public partial class PasslePost : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public new const string ModelTypeAlias = "passlePost";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PasslePost, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public PasslePost(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Authors
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("authors")]
		public virtual global::System.Collections.Generic.IEnumerable<global::PassleSync.Core.Models.Content.Umbraco.PostAuthor> Authors => this.Value<global::System.Collections.Generic.IEnumerable<global::PassleSync.Core.Models.Content.Umbraco.PostAuthor>>("authors");

		///<summary>
		/// CoAuthors
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("coAuthors")]
		public virtual global::System.Collections.Generic.IEnumerable<global::PassleSync.Core.Models.Content.Umbraco.PostAuthor> CoAuthors => this.Value<global::System.Collections.Generic.IEnumerable<global::PassleSync.Core.Models.Content.Umbraco.PostAuthor>>("coAuthors");

		///<summary>
		/// ContentTextSnippet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("contentTextSnippet")]
		public virtual string ContentTextSnippet => this.Value<string>("contentTextSnippet");

		///<summary>
		/// EstimatedReadTimeInSeconds
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("estimatedReadTimeInSeconds")]
		public virtual int EstimatedReadTimeInSeconds => this.Value<int>("estimatedReadTimeInSeconds");

		///<summary>
		/// FeaturedItemEmbedProvider
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("featuredItemEmbedProvider")]
		public virtual string FeaturedItemEmbedProvider => this.Value<string>("featuredItemEmbedProvider");

		///<summary>
		/// FeaturedItemEmbedType
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("featuredItemEmbedType")]
		public virtual string FeaturedItemEmbedType => this.Value<string>("featuredItemEmbedType");

		///<summary>
		/// FeaturedItemHtml
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("featuredItemHtml")]
		public virtual string FeaturedItemHtml => this.Value<string>("featuredItemHtml");

		///<summary>
		/// FeaturedItemMediaType
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("featuredItemMediaType")]
		public virtual string FeaturedItemMediaType => this.Value<string>("featuredItemMediaType");

		///<summary>
		/// FeaturedItemPosition
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("featuredItemPosition")]
		public virtual string FeaturedItemPosition => this.Value<string>("featuredItemPosition");

		///<summary>
		/// ImageUrl
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("imageUrl")]
		public virtual string ImageUrl => this.Value<string>("imageUrl");

		///<summary>
		/// IsFeaturedOnPasslePage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("isFeaturedOnPasslePage")]
		public virtual bool IsFeaturedOnPasslePage => this.Value<bool>("isFeaturedOnPasslePage");

		///<summary>
		/// IsFeaturedOnPostPage
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("isFeaturedOnPostPage")]
		public virtual bool IsFeaturedOnPostPage => this.Value<bool>("isFeaturedOnPostPage");

		///<summary>
		/// IsRepost
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("isRepost")]
		public virtual bool IsRepost => this.Value<bool>("isRepost");

		///<summary>
		/// OpensInNewTab
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("opensInNewTab")]
		public virtual bool OpensInNewTab => this.Value<bool>("opensInNewTab");

		///<summary>
		/// PassleShortcode
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("passleShortcode")]
		public virtual string PassleShortcode => this.Value<string>("passleShortcode");

		///<summary>
		/// PostContentHtml
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("postContentHtml")]
		public virtual string PostContentHtml => this.Value<string>("postContentHtml");

		///<summary>
		/// PostShortcode
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("postShortcode")]
		public virtual string PostShortcode => this.Value<string>("postShortcode");

		///<summary>
		/// PostTitle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("postTitle")]
		public virtual string PostTitle => this.Value<string>("postTitle");

		///<summary>
		/// PostUrl
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("postUrl")]
		public virtual string PostUrl => this.Value<string>("postUrl");

		///<summary>
		/// PublishedDate
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("publishedDate")]
		public virtual string PublishedDate => this.Value<string>("publishedDate");

		///<summary>
		/// QuoteText
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("quoteText")]
		public virtual string QuoteText => this.Value<string>("quoteText");

		///<summary>
		/// QuoteUrl
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("quoteUrl")]
		public virtual string QuoteUrl => this.Value<string>("quoteUrl");

		///<summary>
		/// ShareViews
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("shareViews")]
		public virtual global::System.Collections.Generic.IEnumerable<global::PassleSync.Core.Models.Content.Umbraco.PostShareViews> ShareViews => this.Value<global::System.Collections.Generic.IEnumerable<global::PassleSync.Core.Models.Content.Umbraco.PostShareViews>>("shareViews");

		///<summary>
		/// Tags
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("tags")]
		public virtual global::System.Collections.Generic.IEnumerable<string> Tags => this.Value<global::System.Collections.Generic.IEnumerable<string>>("tags");

		///<summary>
		/// TotalLikes
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("totalLikes")]
		public virtual int TotalLikes => this.Value<int>("totalLikes");

		///<summary>
		/// TotalShares
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("totalShares")]
		public virtual int TotalShares => this.Value<int>("totalShares");

		///<summary>
		/// Tweets
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "8.18.5")]
		[ImplementPropertyType("tweets")]
		public virtual global::System.Collections.Generic.IEnumerable<global::PassleSync.Core.Models.Content.Umbraco.PostTweet> Tweets => this.Value<global::System.Collections.Generic.IEnumerable<global::PassleSync.Core.Models.Content.Umbraco.PostTweet>>("tweets");
	}
}
