//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.1.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace PassleSync.Core.Models.Content.Umbraco
{
	/// <summary>Passle Author</summary>
	[PublishedModel("passleAuthor")]
	public partial class PassleAuthor : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const string ModelTypeAlias = "passleAuthor";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PassleAuthor, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public PassleAuthor(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// AvatarUrl
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("avatarUrl")]
		public string AvatarUrl => this.Value<string>("avatarUrl");

		///<summary>
		/// Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("description")]
		public string Description => this.Value<string>("description");

		///<summary>
		/// EmailAddress
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("emailAddress")]
		public string EmailAddress => this.Value<string>("emailAddress");

		///<summary>
		/// FacebookProfileLink
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("facebookProfileLink")]
		public string FacebookProfileLink => this.Value<string>("facebookProfileLink");

		///<summary>
		/// InstagramProfileLink
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("instagramProfileLink")]
		public string InstagramProfileLink => this.Value<string>("instagramProfileLink");

		///<summary>
		/// LinkedInProfileLink
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("linkedInProfileLink")]
		public string LinkedInProfileLink => this.Value<string>("linkedInProfileLink");

		///<summary>
		/// LocationCountry
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("locationCountry")]
		public string LocationCountry => this.Value<string>("locationCountry");

		///<summary>
		/// LocationDetail
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("locationDetail")]
		public string LocationDetail => this.Value<string>("locationDetail");

		///<summary>
		/// Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("passleName")]
		public string PassleName => this.Value<string>("passleName");

		///<summary>
		/// PersonalLinks
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("personalLinks")]
		public Newtonsoft.Json.Linq.JToken PersonalLinks => this.Value<Newtonsoft.Json.Linq.JToken>("personalLinks");

		///<summary>
		/// PhoneNumber
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("phoneNumber")]
		public string PhoneNumber => this.Value<string>("phoneNumber");

		///<summary>
		/// PinterestProfileLink
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("pinterestProfileLink")]
		public string PinterestProfileLink => this.Value<string>("pinterestProfileLink");

		///<summary>
		/// ProfileUrl
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("profileUrl")]
		public string ProfileUrl => this.Value<string>("profileUrl");

		///<summary>
		/// RoleInfo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("roleInfo")]
		public string RoleInfo => this.Value<string>("roleInfo");

		///<summary>
		/// Shortcode
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("shortcode")]
		public string Shortcode => this.Value<string>("shortcode");

		///<summary>
		/// SkypeProfileLink
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("skypeProfileLink")]
		public string SkypeProfileLink => this.Value<string>("skypeProfileLink");

		///<summary>
		/// StumbleUponProfileLink
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("stumbleUponProfileLink")]
		public string StumbleUponProfileLink => this.Value<string>("stumbleUponProfileLink");

		///<summary>
		/// SubscribeLink
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("subscribeLink")]
		public string SubscribeLink => this.Value<string>("subscribeLink");

		///<summary>
		/// TagLineCompany
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("tagLineCompany")]
		public string TagLineCompany => this.Value<string>("tagLineCompany");

		///<summary>
		/// TwitterScreenName
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("twitterScreenName")]
		public string TwitterScreenName => this.Value<string>("twitterScreenName");

		///<summary>
		/// VimeoProfileLink
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("vimeoProfileLink")]
		public string VimeoProfileLink => this.Value<string>("vimeoProfileLink");

		///<summary>
		/// XingProfileLink
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("xingProfileLink")]
		public string XingProfileLink => this.Value<string>("xingProfileLink");

		///<summary>
		/// YouTubeProfileLink
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.1.0")]
		[ImplementPropertyType("youTubeProfileLink")]
		public string YouTubeProfileLink => this.Value<string>("youTubeProfileLink");
	}
}
